// This file is generated by scripts/content/build-runtime.js.
// It gives the Expo app one stable import surface for committed runtime content.
import type { Anaphora, AnaphoraMetadata, LiturgicalText } from '@/data/types';

const service_qidan: LiturgicalText = require('@/data/qidan.json');
const service_serate_qidase: LiturgicalText = require('@/data/serate-qidase.json');
const seasonalsData: LiturgicalText = require('@/data/seasonals.json');
const anaphoraMetadata: AnaphoraMetadata[] = require('@/data/anaphoras/anaphoras.json');
const anaphora_saint_john_chrysostom: Anaphora = require('@/data/anaphoras/saint-john-chrysostom.json');
const anaphora_saint_mary: Anaphora = require('@/data/anaphoras/saint-mary.json');
const anaphora_apostles: Anaphora = require('@/data/anaphoras/apostles.json');
const anaphora_saint_basil: Anaphora = require('@/data/anaphoras/saint-basil.json');
const anaphora_saint_gregory: Anaphora = require('@/data/anaphoras/saint-gregory.json');
const anaphora_saint_epiphanius: Anaphora = require('@/data/anaphoras/saint-epiphanius.json');
const anaphora_saint_cyril: Anaphora = require('@/data/anaphoras/saint-cyril.json');
const anaphora_saint_james_sarugh: Anaphora = require('@/data/anaphoras/saint-james-sarugh.json');
const anaphora_saint_james_nisibis: Anaphora = require('@/data/anaphoras/saint-james-nisibis.json');
const anaphora_saint_dioscorus: Anaphora = require('@/data/anaphoras/saint-dioscorus.json');
const anaphora_our_lord: Anaphora = require('@/data/anaphoras/our-lord.json');
const anaphora_saint_john_thunder: Anaphora = require('@/data/anaphoras/saint-john-thunder.json');
const anaphora_three_hundred_eighteen: Anaphora = require('@/data/anaphoras/three-hundred-eighteen.json');
const anaphora_saint_athanasius: Anaphora = require('@/data/anaphoras/saint-athanasius.json');

// These maps are generated from canonical source docs during the local build step.
export const SERVICE_RUNTIME_MAP: Record<string, LiturgicalText> = {
  'qidan': service_qidan,
  'serate-qidase': service_serate_qidase,
};

export const ANAPHORA_RUNTIME_MAP: Record<string, Anaphora> = {
  'saint-john-chrysostom': anaphora_saint_john_chrysostom,
  'saint-mary': anaphora_saint_mary,
  'apostles': anaphora_apostles,
  'saint-basil': anaphora_saint_basil,
  'saint-gregory': anaphora_saint_gregory,
  'saint-epiphanius': anaphora_saint_epiphanius,
  'saint-cyril': anaphora_saint_cyril,
  'saint-james-sarugh': anaphora_saint_james_sarugh,
  'saint-james-nisibis': anaphora_saint_james_nisibis,
  'saint-dioscorus': anaphora_saint_dioscorus,
  'our-lord': anaphora_our_lord,
  'saint-john-thunder': anaphora_saint_john_thunder,
  'three-hundred-eighteen': anaphora_three_hundred_eighteen,
  'saint-athanasius': anaphora_saint_athanasius,
};

export const SEASONALS_DATA = seasonalsData;
export const ANAPHORA_METADATA = anaphoraMetadata;

// Route screens use these helpers so they never import individual JSON files directly.
export function loadServiceRuntime(id: string): LiturgicalText | null {
  return SERVICE_RUNTIME_MAP[id] ?? null;
}

export function loadAnaphoraRuntime(id: string): Anaphora | null {
  return ANAPHORA_RUNTIME_MAP[id] ?? null;
}

